version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cloud_storage_db
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - file_storage:/app/uploads

volumes:
  postgres_data:
  file_storage: